name: broadcast

on:
  repository_dispatch:
    types: [build_update]

permissions:
  contents: write

jobs:
  Update:
    uses: martis99/build/.github/workflows/build_update.yml@main
    with:
      run_id: ${{github.event.client_payload.run_id}}

  Broadcast:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [build, cutils]

    steps:
      - name: Notify
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: 'martis99',
              repo: "${{matrix.repo}}",
              event_type: 'build_update',
              client_payload: {
                run_id: "${{github.run_id}}"
              }
            });
          github-token: ${{secrets.PAT}}
